AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  SnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: email@example.com
          Protocol: email
      TopicName: alarm-action
  CloudWatchAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: vpc_routetable_changes
      AlarmDescription: >-
        A CloudWatch Alarm that triggers when changes are made to a VPC's Route
        Table.
      MetricName: VpcRouteTableEventCount
      Namespace: CloudTrailMetrics
      Statistic: Sum
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '1'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - Ref: SnsTopic
      TreatMissingData: notBreaching
  MetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: ''
      FilterPattern: >-
        { ($.eventName = AssociateRouteTable) || ($.eventName = CreateRoute) ||
        ($.eventName = CreateRouteTable) || ($.eventName = DeleteRoute) ||
        ($.eventName = DeleteRouteTable) || ($.eventName = ReplaceRoute) ||
        ($.eventName = ReplaceRouteTableAssociation) || ($.eventName =
        DisassociateRouteTable) }
      MetricTransformations:
        - MetricValue: '1'
          MetricNamespace: CloudTrailMetrics
          MetricName: VpcRouteTableEventCount
Parameters: {}
Metadata: {}
Conditions: {}
